services:
  - type: web
    name: joelle-e-portfolio
    runtime: docker
    plan: free
    dockerfilePath: backend/docker-compose.yml
    rootDir: backend
    envVars:
      - key: SUPABASE_URL
        value: https://bedzvtmzhrwujiaukjvl.supabase.co
      - key: SUPABASE_SERVICE_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJlZHp2dG16aHJ3dWppYXVranZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjUyNjkzNDAsImV4cCI6MjA4MDg0NTM0MH0.3heykJxByfCSpvJkXgOw3m503IkvYm7pxDsQ4-hSAJ8
      - key: SUPABASE_ANON_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJlZHp2dG16aHJ3dWppYXVranZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjUyNjkzNDAsImV4cCI6MjA4MDg0NTM0MH0.3heykJxByfCSpvJkXgOw3m503IkvYm7pxDsQ4-hSAJ8