services:
  - type: web
    name: joelle-e-portfolio
    runtime: docker
    plan: free
    build:
      context: ./backend
      dockerfile: docker-compose.yml
    envVars:
      - key: SUPABASE_URL
        value: https://bedzvtmzhrwujiaukjvl.supabase.co
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
    startCommand: docker compose up